// App level requests
const HEADLESS_CAS_LOGIN_REQUESTED = 'application/HEADLESS_CAS_LOGIN_REQUESTED'
const SHIB_LOGIN_REQUESTED = 'application/SHIB_LOGIN_REQUESTED'
const LOCAL_LOGIN_REQUESTED = 'application/LOCAL_LOGIN_REQUESTED'
const FACEBOOK_LOGIN_REQUESTED = 'application/FACEBOOK_LOGIN_REQUESTED'
const LOG_OUT_REQUESTED = 'auth/LOG_OUT_REQUESTED'

// System level responses
const GET_TOKEN_SUCCEEDED = 'auth/GET_TOKEN_SUCCEEDED'
const TOKEN_REFRESH_SUCCEEDED = 'auth/TOKEN_REFRESH_SUCCEEDED'
const TOKEN_REFRESH_FAILED = 'auth/TOKEN_REFRESH_FAILED'
const LOGIN_FAILED = 'auth/LOGIN_FAILED'

export function createAction(type, payload) {	
	return Object.assign({}, {type}, payload)
}

export default {
	HEADLESS_CAS_LOGIN_REQUESTED, SHIB_LOGIN_REQUESTED, LOCAL_LOGIN_REQUESTED, FACEBOOK_LOGIN_REQUESTED, LOG_OUT_REQUESTED,
	GET_TOKEN_SUCCEEDED, TOKEN_REFRESH_FAILED, TOKEN_REFRESH_SUCCEEDED, LOGIN_FAILED
}