// App level requests
const CAS_LOGIN_REQUESTED = 'application/CAS_LOGIN_REQUESTED'
const SHIB_LOGIN_REQUESTED = 'application/SHIB_LOGIN_REQUESTED'
const LOCAL_LOGIN_REQUESTED = 'application/LOCAL_LOGIN_REQUESTED'
const FACEBOOK_LOGIN_REQUESTED = 'application/FACEBOOK_LOGIN_REQUESTED'
const LOG_OUT_REQUESTED = 'LOG_OUT_REQUESTED'

// System level responses
const LOGIN_SUCCEEDED = 'auth/LOGIN_SUCCEEDED'
const LOGIN_FAILED = 'auth/LOGIN_FAILED'

export function createAction(type, payload) {	
	return Object.assign({}, {type}, payload)
}

export default {
	CAS_LOGIN_REQUESTED, SHIB_LOGIN_REQUESTED, LOCAL_LOGIN_REQUESTED, FACEBOOK_LOGIN_REQUESTED, LOG_OUT_REQUESTED,
	LOGIN_SUCCEEDED, LOGIN_FAILED
}