'use strict';

Object.defineProperty(exports, "__esModule", {
	value: true
});
exports.createAction = createAction;
var AUTH_INITIALIZED = 'auth/INITIALIZED';

// App level requests
var HEADLESS_CAS_LOGIN_REQUESTED = 'application/HEADLESS_CAS_LOGIN_REQUESTED';
var CAS_LOGIN_REQUESTED = 'application/CAS_LOGIN_REQUESTED';
var SHIB_LOGIN_REQUESTED = 'application/SHIB_LOGIN_REQUESTED';
var LOCAL_LOGIN_REQUESTED = 'application/LOCAL_LOGIN_REQUESTED';
var FACEBOOK_LOGIN_REQUESTED = 'application/FACEBOOK_LOGIN_REQUESTED';
var LOGIN_REQUESTED = 'auth/LOGIN_REQUESTED';
var LOG_OUT_REQUESTED = 'auth/LOG_OUT_REQUESTED';

// System level responses
var GET_TOKEN_SUCCEEDED = 'auth/GET_TOKEN_SUCCEEDED';
var TOKEN_REFRESH_SUCCEEDED = 'auth/TOKEN_REFRESH_SUCCEEDED';
var TOKEN_REFRESH_FAILED = 'auth/TOKEN_REFRESH_FAILED';
var LOGIN_FAILED = 'auth/LOGIN_FAILED';

function createAction(type, payload) {
	return Object.assign({}, { type: type }, payload);
}

exports.default = {
	AUTH_INITIALIZED: AUTH_INITIALIZED,
	HEADLESS_CAS_LOGIN_REQUESTED: HEADLESS_CAS_LOGIN_REQUESTED,
	CAS_LOGIN_REQUESTED: CAS_LOGIN_REQUESTED,
	SHIB_LOGIN_REQUESTED: SHIB_LOGIN_REQUESTED,
	LOCAL_LOGIN_REQUESTED: LOCAL_LOGIN_REQUESTED,
	FACEBOOK_LOGIN_REQUESTED: FACEBOOK_LOGIN_REQUESTED,
	LOGIN_REQUESTED: LOGIN_REQUESTED,
	LOG_OUT_REQUESTED: LOG_OUT_REQUESTED,
	GET_TOKEN_SUCCEEDED: GET_TOKEN_SUCCEEDED,
	TOKEN_REFRESH_FAILED: TOKEN_REFRESH_FAILED,
	TOKEN_REFRESH_SUCCEEDED: TOKEN_REFRESH_SUCCEEDED,
	LOGIN_FAILED: LOGIN_FAILED
};